[package]
name = "midi-mixer"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5.0.1"
midir = "0.10.0"
pulsectl-rs = "0.3.2"
serde = {version ="1.0.210", features = ["derive"]}
toml = "0.8.19"
