midi_controller_name = "nanoKONTROL2:nanoKONTROL2 nanoKONTROL2 _ CTR 28:0"

[controls]
[controls.buttons]
[controls.buttons.button1]
control = 48
channel = 0
trigger = 127

[controls.faders]
[controls.faders.fader1]
channel = 0
control = 0
min = 0
max = 127

[groups]
  [groups.group1]
    volume_control = ["fader1"]
    mute = ["button1"]

  [groups.group2]
    volume_control = []
    mute = []

[mapping]
  "group1" = "firefox"
  "group2" = "application_2"

